### ISSUE TITLE
latexpdf target does not render wavedrom

### ISSUE THREAD

**Issue by dryodon** [bavovanachte/sphinx-wavedrom#6]
Wavedrom graphics are not visible when sphinx building for pdf.
fyi, see:
https://github.com/mossblaser/WaveDromTikZ

**Comment by bavovanachte** [comment]
Hi,

This is mainly due to the way the diagrams are rendered. They are not converted to png/jpg and then inserted, but are inserted at the end as a raw html block, and rendered using the wavedrom Javascript libraries. So it is only built around html documents.

At the time of writing the plugin, there was a cmdline utility available, but IIRC it wasn't very stable. This might be different now. I'll take a look.

Anyhow, it's a valid concern, but not an easy or quick fix. Could borrow some ideas at the plantuml plug-in.

**Comment by bavovanachte** [comment]
Do you have a specific reason for recommending the TikZ implementation?

I would personally be more inclined to use the official wavedrom cli instead (https://github.com/wavedrom/cli), especially given the fact that I would like to keep supporting the browser-rendering option, and keep the 2 options consistent

**Comment by SteinHeselmans** [comment]
Borrowing ideas from plantuml plugin is a good idea, i did the same when i started this openscad plugin (https://github.com/SteinHeselmans/sphinx-openscad-extension). First results in that project are good, but that one still needs some work and tests to get a first alpha out...

**Comment by oharboe** [comment]
I'd love to use this plugin, it is easy to use and looks *great*, but I have to deliver my doc in PDF format.

**Comment by wallento** [comment]
Hi, I have added this feature. Please give PR #8 a try!
